### ISSUE TITLE
 Ran out of memory trying to allocate 392.00MiB.

### ISSUE THREAD

**Issue by JorgeVilchis** [TensorVision/TensorVision#58]
This function used in demo.py from KittiDetect demo is throwing an errror:

      core.load_weights(logdir, sess, saver)

Log:
 I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 1024 totalling 3.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 7 Chunks of size 2048 totalling 14.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 4096 totalling 8.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 6912 totalling 6.8KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 16384 totalling 32.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 32768 totalling 32.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 147456 totalling 144.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 294912 totalling 288.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 589824 totalling 576.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1179648 totalling 1.12MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 2359296 totalling 4.50MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 4718592 totalling 4.50MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 9437184 totalling 45.00MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 90118400 totalling 85.94MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 142.15MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                   241172480
InUse:                   149055488
MaxInUse:                241154048
NumAllocs:                      77
MaxAllocSize:             90118400

W tensorflow/core/common_runtime/bfc_allocator.cc:274] *__*****___**************____*___***********_________________******************************xxxxxxxxx
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 392.00MiB.  See logs for memory state.
Traceback (most recent call last):
  File "demo.py", line 220, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 160, in main
    core.load_weights(logdir, sess, saver)
  File "incl/tensorvision/core.py", line 40, in load_weights
    saver.restore(sess, checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[Node: save/RestoreV2_27/_25 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_144_save/RestoreV2_27", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

====

No idea what the issue could be.

**Comment by MartinThoma** [comment]
Which GPU do you have?

**Comment by JorgeVilchis** [comment]
It is a Titan X , I can sent you the details once I get to my computer.

**Comment by MarvinTeichmann** [comment]
>  This  function used in demo.py from KittiDetect demo is throwing an errror:

Are you referring to the [KittiBox](https://github.com/MarvinTeichmann/KittiBox) repository?

The error message indicates, that you do not have enough GPU memory. The code should work with 6GB RAM, 4GB RAM have not been tested. If you just want to run demo.py you can run it on CPU. In addition the [KittiSeg](https://github.com/MarvinTeichmann/KittiSeg) code has slightly less memory requirements. 

A possible issue might be, that other processes take up a large shunk of memory. Inspect how much free memory is available using `nvidia-smi`and stop other processes if necessary.

**Comment by MarvinTeichmann** [comment]
As a small hint. Watch out for the following line:

> 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
> name: GeForce GTX 1080
> major: 6 minor: 1 memoryClockRate (GHz) 1.8095
> pciBusID 0000:01:00.0
> Total memory: 7.91GiB
> Free memory: 266.44MiB

If free memory is only a couple of hundreds MiB big (like in the above example) something is wrong.
